### ISSUE TITLE
incorrect italics on snakecase words

### ISSUE THREAD

**Issue by heisters** [hallison/vim-markdown#1]
foo_bar gets highlighted as htmlItalic. Changing the regex for htmlItalic to 

`syntax region htmlItalic  start=/\\\@<!\(^\|\A\)\@=\<_\@<!__\@!/       end=/\\\@<!_\@<!__\@!\($\|\A\)\@=/       contains=htmlBold,@Spell`

fixes the problem. The only addition is `\<` before the single `_` in the start expression.

**Comment by hallison** [comment]
Yep! You're right! And I checked other problem when writing `__foo_bar__`. Your fix solves this problem. Thanks. I'll release a new version.
