### ISSUE TITLE
inline footnotes

### ISSUE THREAD

**Issue by mren** [hallison/vim-markdown#10]
Could it be possible to include inline footnotes

```
this is text^[inline footnote]. nothing to see here.
```

This is not in the standard version of markdown, but pandoc uses this feature.
If inline footnotes are used now, the whole document is underlined.

**Comment by gadamiak** [comment]
PHP Markdown uses them too. The underlining, however, results from other bug, see #9.

**Comment by mren** [comment]
thank you :)

**Comment by hallison** [comment]
Hello folks,

Actually, I am rewriting all sources of the plugin. No commits, yet. Please, wait for good news.

Thanks for all.

**Comment by gadamiak** [comment]
Great news! I'm keeping my fingers crossed ;) I'll post another improvement requests soon -- fenced code blocks and definition lists from PHP Markdown and folding for headings and lists.

**Comment by hallison** [comment]
Hi folks,

I thought about adding other file types that run markdown.vim and add other features like PHP Markdown syntax or Markdown extended.

Any suggestions?

**Comment by gadamiak** [comment]
PHP Markdown Extra is what I use, actually. It has some very [useful extensions to Markdown](http://michelf.com/projects/php-markdown/extra/) like definition lists, simple tables, fenced code blocks and abbreviations. It features footnotes too. See also issue #12.

So, yes, go with it, please :D

**Comment by mren** [comment]
Perhaps you are interested in implementing some of [Pandocs modifications to markdown](http://johnmacfarlane.net/pandoc/README.html)
