### ISSUE TITLE
Error when loading via pathogen

### ISSUE THREAD

**Issue by jgallen23** [hallison/vim-markdown#11]
I get this error when I load via pathogen
<code>Error detected while processing function pathogen#helptags:
line    3:
E151: No match: .vim/bundle/vim-markdown/doc/*
</code>

**Comment by hallison** [comment]
Hi Greg,

This problem will be solved in the future changes.

Regards and thanks for the your contributions.

**Comment by dennishostetler** [comment]
I had the same issue. You can get around it by doing a `touch markdown.txt` in the doc directory.

**Comment by hallison** [comment]
This error will be fixed in the version 2.0.0. I'll release a beta version. Please, install and try use this new version to help to improve this plugin. See the [2.0.0-beta](https://github.com/hallison/vim-markdown/tree/2.0.0-beta) branch.

Thans for your contribution.
