### ISSUE TITLE
No syntax highlighting

### ISSUE THREAD

**Issue by jgallen23** [hallison/vim-markdown#13]
I am using pathogen, but not getting any syntax highlighting

<img src="http://f.cl.ly/items/3A3h140Y2Y1Y0k3C043j/Screen%20shot%202011-05-31%20at%202.54.28%20PM.png"/>

**Comment by peplin** [comment]
I just had this happen too, but digging a bit into Pathogen I found this:

"Note that you need to invoke the pathogen functions before invoking "filetype plugin indent on" if you want it to load ftdetect files. On Debian (and probably other distros), the system vimrc does this early on, so you actually need to "filetype off" before "filetype plugin indent on" to force reloading." 

The new recommended way of loading pathogen is `pathogen#infect()` which takes care of everything for you (https://github.com/tpope/vim-pathogen/pull/26) - that fixed this issue with vim-markdown for me.

**Comment by jgallen23** [comment]
@peplin - that worked great!  Thanks.  Closing.
