### ISSUE TITLE
Which snippets plugin works with included snippets?

### ISSUE THREAD

**Issue by fncll** [hallison/vim-markdown#24]
There are a multitude of snippets programs for vim... which one is the snippets file included with this plugin designed for? I can't seem to find any indication in the documentation

**Comment by hallison** [comment]
fncll,

This plugin uses, as described in [README.mkd](http://git.io/_9Ydgg) file, [the snipMate](http://git.io/ZCCuew) to load snippets.

Thanks for your contribution.

**Comment by fncll** [comment]
Don't know how I missed that! Thanks so much.

c

On Fri, Nov 25, 2011 at 6:43 AM, Hallison Batista
reply@reply.github.com
wrote:
