### ISSUE TITLE
Need a formal "how-to" doc for vim-markdown

### ISSUE THREAD

**Issue by weijianwen** [hallison/vim-markdown#27]
Hi, hallison. I suggest adding a formal "how-to" doc for vim-markdown. 

_:help_ is always the first place I would refer to, every time I install a new vim script. However, vim-markdown makes me kind of confused: yes it works -- now vim highlights my markdown file correctly; but wait, what should I do next with vim-markdown?

I use [pathogen](https://github.com/tpope/vim-pathogen) to manage my vim scripts. I apologize if I miss anything I should read before using vim-makrdown.

**Comment by hallison** [comment]
Hi @weijianwen,

The documentation is under development. Please be patience. The vim-markdown is a syntax highlight for Vim editor. But, it will have more features in the future as a compiler command and support to call URL shorten scripts.

Try use the 2.0.0beta branch version.

Thanks for your contribution.

**Comment by weijianwen** [comment]
It is me that should say "thank you". vim-markdown is one of my favorite handy plug-ins.

I have a propose. [Pandoc](http://johnmacfarlane.net/pandoc/) is a nice tool to convert between various markup formats, such as markdown, HTML, TeX, etc al. Pandoc has its extension to the original Markdown language, which makes markdown a more usable language in composing normal documents, other than web pages. Do you plan to support Pandoc's  markdown language and the tool?

Forget it if the idea doesn't make sense.

**Comment by hallison** [comment]
@weijianwen,

The Pandoc is a excelent tool to process the lightweight texts. And to answer to your propose, yes, I have plans to support the Markdown-Extra syntax (that a built-in in Pandoc). But this feature will be expanded by the file type detection. Wait for vim-markdown v2.0.0.
