### ISSUE TITLE
Recognize .md as markdown

### ISSUE THREAD

**Issue by weijianwen** [hallison/vim-markdown#28]
Hi, hallison. Is it possible to recognize `.md` as markdown files? `.md` seems to be popular on GitHub. Thanks

**Comment by hallison** [comment]
Hi @weijianwen,

The extension `.md` has been configured in `ftdetect/markdown.vim` file. Please, see this file.

**Comment by weijianwen** [comment]
Hi, @hallison 

   Currently I'm using the HEAD version at master branch. I've checked `ftdetect/markdown.vim`. Yes, `.md` is there, but vim-markdown does not highlight it correctly. Is there any way I can help to figure out what's going on? Thanks.

   The details are as follows.

```
commit 10073c3a3c363c34681c2e37ae29e9675e2cde90
Merge: 8068cf3 5f692c2
Author: Hallison Batista <hallison.batista@gmail.com>
Date:   Tue Mar 6 20:07:20 2012 -0800

    Merge pull request #26 from scy/master

    Recognize .mdwn files as Markdown
```

I use a mini file to test. The content is:

```
# Hello,world.
+ Hello
+ World.
```

I save it as `hello.md` and `hello.mkd`. 

The following is hello.md. It does not highlight correctly

![md_wrong](http://dl.dropbox.com/u/3829274/md_wrong.png)

The following is hello.mkd. It is OK.

![mkd_right](http://dl.dropbox.com/u/3829274/mdk_correct.png)

**Comment by weijianwen** [comment]
Hi, @hallison 

  I've figured out why vim-markdown did not highlight `.md` files correctly in my vim environment. The problem has nothing to do with vim-markdown. Instead, there's something wrong with my Pathogen conf, which starts all the vim plug-ins.

  Now vim-markdown works fine for me. I am really sorry. Good luck to you.

**Comment by hallison** [comment]
@weijianwen,

Thanks for your contribution. Try use the 2.0beta and send me a feedback.
