### ISSUE TITLE
doc/* files aren't found by pathogen#helptags()

### ISSUE THREAD

**Issue by tupton** [hallison/vim-markdown#3]
Everything but helptags seems to work fine when using this plugin with pathogen. 

```
Error detected while processing function pathogen#helptags:
line    3:
E151: No match: ~/.vim/bundle/markdown/doc/*
```

I'm not sure if this is a pathogen issue or an issue with these doc files, but I figured I should let you know that it exists.

**Comment by tupton** [comment]
For what it's worth, calling `:helptags ~/.vim/bundle/markdown/doc/releases` seems to work. I think there's some confusion between using `doc/` for changelog-style release notes (which is what this plugin is doing) and using `doc/` for vim-related plugin documentation (which is what pathogen assumes is in `doc/`.)

**Comment by hallison** [comment]
Hi Thomas,

The path `doc/releases` should only used in repository. It's a summary of changes for developers. When I create the package for distribution, I don't use this directory.

The software must be deployed by a system package and not by directly from repository. In this case, the software should be "builded" using a build system.

This project uses the `bake` program for this task. Please, see [Bash-Toolbox](https://github.com/codigorama/bash-toolbox) for more information.

I'm very grateful to you by use this plugin and by report this issue.

Best regards.

**Comment by tupton** [comment]
Downloading the vimball and installing it worked fine, but I had to manually move the built files to bundle/markdown. I'll miss using the markdown plugin as a git submodule because I won't be able to update as easily, but it does work well.

Thanks for your help.

**Comment by tow8ie** [comment]
I had the same problem when using this repo as a submodule in conjunction with pathogen. Try to use this repo which works for me: https://github.com/vim-scripts/Markdown.git

http://vim-scripts.org/ is definitely worth a look. Their account hosts repos that are (beta) mirrors of the vim.org scripts but it works fine for me so far.
