### ISSUE TITLE
Support for gollum style links

### ISSUE THREAD

**Issue by lukebakken** [hallison/vim-markdown#30]
Hello!

Thanks for the excellent syntax file. I'm wondering what would be necessary to support [[ | ]] style links like those used by the gollum wiki (https://github.com/github/gollum/)

I'll try adding the support myself, but I'm new to vim's syntax file format.

**Comment by hallison** [comment]
I'll write several extensions to vim-markdown and I'll include this syntax. Thanks to use my project. The gollum is awesome project.

Regards.

**Comment by lukebakken** [comment]
Thanks Hallison! I'll keep an eye on this and will test as soon as it's ready.
