### ISSUE TITLE
Backticks in "code" snippet needs to be escaped

### ISSUE THREAD

**Issue by tupton** [hallison/vim-markdown#4]
The backtick code snippet does not work as-is: the backticks in the snippet itself need to be escaped:

```
# `code`
snippet `
    \`${1}\`${2}
```

Note that the backtick that serves as the snippet "trigger" _does not_ need to be escaped.

**Comment by hallison** [comment]
Yep! I don't seen this bug. I'll change the snippet and I'll release a new bug fix version. Thanks for your contribution.

**Comment by hallison** [comment]
New version. See in http://www.vim.org/scripts/script.php?script_id=2882.

**Comment by tupton** [comment]
Thanks for letting me know about the new release! It looks good.
