### ISSUE TITLE
Multi-paragraph list items

### ISSUE THREAD

**Issue by dubiousjim** [hallison/vim-markdown#5]
When I use multi-paragraph numbered or bulleted lists, all paragraphs after the first are treated as <pre><code> blocks. It doesn't matter whether the intervening line is empty, or consists of only a single tab, or any other whitespace-only variant I can figure out.

**Comment by hallison** [comment]
-- Ok! Houston, we have a problem. (tzzz)

-- Ok! We'll check and solve it. (tzzz)

Thanks for your contribution.

**Comment by di** [comment]
Hi @profjim, could you share a brief snippet which reproduces this issue?

**Comment by dubiousjim** [comment]
<pre>
Blah blah as in this list:

*   This is the first item.

    This should still be the first list item, but it's colored as if 
    it were a &lt;pre&gt;&lt;code&gt; block, instead.

*   This is the second item.

    This should still be the second item.

List has ended.
</pre>

**Comment by di** [comment]
Hi @profjim, I've fixed this issue in my fork. If you don't feel like waiting for @hallison to pull the changes & publish a new version, you fix this locally by editing your `~/.vim/syntax/markdown.vim` and replacing the line:

```
syntax match  mkdListItem  "^\s*[-*+]\s\+"
```

with:

```
syntax match  mkdListItem  /^\s*[-*+]\s\+.*\n\(\(^.\+\n\)*\n\?\)\(\(^\(\s\{4}\|\t\)\+.*\n\)\(^.\+\n\)*\n\?\)*/
```

**Comment by dubiousjim** [comment]
Thanks dustingram! I'm not sure whether this is the right solution though. Consider the following test snippet:

<pre><code>
Initial text.
 
1.  Numbered list item.

2.  Another numbered list item.

    Continuation of second numbered list item.
 
End of numbered list.

    This should really be a `&lt;pre&gt;` block, and the following
    entity shouldn't be special: &amp;gt.
 
Here is an unordered list:

*   This is unordered item one.
*   This is unordered item two.

Here is another unordered list:

*   This is first item.

*   This is second item, the following should be marked special: `&lt;pre&gt;`
    and so too should this: &amp;gt.
 
    Continuation of the second unordered list item.

*   Third item, with an embedded `&lt;pre&gt;` block:

        This should really be a `&lt;pre&gt;` block, and the following
        entity shouldn't be special: &amp;gt.

    Continuation of third item.

Here is the body.
</code></pre>


With the original syntax plug-in, the only problem is that all of the "Continuation..." lines are marked up as &lt;pre&gt; blocks. With your modifications, that may be partly fixed, but several other things are broken.

I say "partly", because the first "Continuation..." line for the numbered list item, is still incorrectly colored as being a &lt;pre&gt;&lt;code&gt; block.

What is then broken is that the entire unordered list is colored the same as the bullet item (on my setup, that's yellow). In the numbered list, the number and following period are colored that way, but the text of the list item is colored plain (except for the embedded "special" items in the list item, like the entity code). But in the unordered list, everything is colored yellow, and there's no difference between the list item text and the entitty code, and also no difference between the list item text and the embedded &lt;pre&gt;&lt;code&gt; block.

**Comment by di** [comment]
Hi @profjim, thanks for the updated snippet. I didn't realize this was affecting enumerated lists as well.

The difference you're seeing in bullet/number highlighting (in the original) and full-list highlighting (in this version) stems from the fact that originally, entire lists were not being matched & highlighted, only their bullets/numbers, leaving the rest of the list to be matched as 'regular' body text.

The latest commit in my fork (18e18689bcb65fbf750155e882edb61ce92525ce) should fix all this. Specifically: inline code, code blocks, and emphasized text are correctly highlighted within lists, and lists are highlighted in their entirety.

Please feel free to give it a test and see you can find any additional issues. The easiest way to do so is to replace your `~/.vim/syntax/markdown.vim` with this latest raw version: https://github.com/dustingram/vim-markdown/raw/master/syntax/markdown.vim

Thanks for your help!

**Comment by dubiousjim** [comment]
Hi, thanks, that looks a lot better. So now the whole list items are yellow, not just the bullets or numbers. As I understand you, that's what you intend. Some of the markup within the list item is correctly hilighted: For example in the unordered item "This is second item, the following should be special: `&lt;pre&gt;` but it's not, and neither is this: &amp;gt." in my test snippet above, the `&lt;pre&gt;` is hilighted, but the entity isn't. Can you get the entity to be hilighted too?

Also, I'm not sure what you were aiming for with the embedded code block inside the third unordered list item. I'd have expected it to all be hilighted the same as an unembedded code block (green on my setup), but this new syntax file now makes it come out highlighted yellow, like the list item it's embedded in. Also, here I expect the opposite behavior with embedded markup: since this is a code block, neither tags nor entities should be marked special. However, what I see is that just like in a regular list item, here tags are marked special but entities aren't. Is it possible to get the syntax file to recognize that this is an embedded code block, and so to mark the whole block appropriately, with tags and entities getting no special treatment?

**Comment by di** [comment]
Hi @profjim, my fork now highlights special HTML characters ('entities') in both types of lists. The raw file linked above has been updated as well.

Two things:
1. Make sure that special HTML characters are closed with a `;`, e.g. `&gt;` and not `&gt.`, otherwise they are not valid and won't be highlighted.
2. Make sure that you don't have whitespace on empty lines, as this will affect the highlighter's interpretation of the embedded code blocks, which must be surrounded by completely empty lines.

Here's what the latest version looks like for me:
![vim-markdown screenshot](http://i.imgur.com/mm5Ym.png)

And here's the (slightly modified) example snippet which produced it:

```
Initial text.

1.  Numbered list item.

2.  Another numbered list item.

    Continuation of second numbered list item.

End of numbered list.

    This should really be a `<pre>` block, and the following
    entity shouldn't be special: &gt;.

Here is an unordered list:

*   This is unordered item one.
*   This is unordered item two.

Here is another unordered list:

*   This is first item.

*   This is second item, the following should be marked special: `<pre>`
    and so too should this: &gt;.

    Continuation of the second unordered list item.

*   Third item, with an embedded `<pre>` block:

        This should really be a `<pre>` block, and the following
        entity shouldn't be special: &gt;.

    Continuation of third item.

Here is the &gt; body. 
```

**Comment by dubiousjim** [comment]
Looks great! And works for me too. In fact it seems to work _even if_ there is whitespace in the lines in between paragraphs of a list item, or between those and an embedded code block.

Thanks for your work!

**Comment by hallison** [comment]
Hi buddies,

Please, I'm so sorry for not responds your comments.

The code written by @dustingram solves the problems and I'll merge this for a new release version.

Thanks you all for the contributions and comments.

**Comment by dubiousjim** [comment]
Hi @hallison, thanks, no worries about the delay. But don't give me credit for the code. I just reported the problem, @dustingram fixed it.

**Comment by hallison** [comment]
Wow! I'm sorry. I typed wrong. I meant @dustingram.

Thanks to @dustingram. Great job, man.
