### ISSUE TITLE
format docs dir layout to be pathogen compatable

### ISSUE THREAD

**Issue by ptone** [hallison/vim-markdown#8]
When I try to clone your repo directing into bundles, I get this error output from pathogen:

Error detected while processing function pathogen#helptags:
line    3:
E151: No match: /Users/preston/.vim/bundle/markdown/doc/*
Error detected while processing function pathogen#helptags:
line    3:
E151: No match: /Users/preston/.vim/bundle/markdown/doc/*

**Comment by hallison** [comment]
Hi ptone,

Try use several solutions reported by [tupton](https://github.com/hallison/vim-markdown/issues/closed#issue/3/comment/606632) in issue #3.

I'm very grateful to you by use this plugin and by report this issue.

Thanks and best regards.
